#:schema node_modules/wrangler/config-schema.json
name = "queue-tracer"
main = "server.js" # Removed the "backend/" prefix
compatibility_date = "2026-06-24"

# Global environment variables accessible in your code via `env.VARIABLE_NAME`
[vars]
ENV = "production"