#:schema node_modules/wrangler/config-schema.json
name = "queue-tracer"
main = "backend/server.js" # Change to "src/index.ts" if you use TypeScript
compatibility_date = "2026-06-24"

# Global environment variables accessible in your code via `env.VARIABLE_NAME`
[vars]
ENV = "production"

# (Optional) If your backend service connects to a Cloudflare D1 Database
# [[d1_databases]]
# binding = "DB"
# database_name = "your-db-name"
# database_id = "your-d1-database-id"